apiVersion: batch/v1
kind: Job
metadata:
  name: open-data-etl-job
  namespace: data-platform
  labels:
    app: open-data-etl-platform
    component: etl
    environment: lab
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: open-data-etl-platform
        component: etl
        environment: lab
    spec:
      restartPolicy: Never
      containers:
        - name: etl
          image: 480415624657.dkr.ecr.us-east-2.amazonaws.com/open-data-etl-platform/etl:latest
          imagePullPolicy: Always
          command: ["python", "-m", "src.main"]
          envFrom:
            - configMapRef:
                name: open-data-etl-config